# -*- coding: utf-8 -*-
"""LABVIII

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eeflbjm220e-YrYVBG5s4bs6tTyJWLHI
"""

pip install ucimlrepo

from ucimlrepo import fetch_ucirepo

# fetch dataset
breast_cancer = fetch_ucirepo(id=14)

# data (as pandas dataframes)
X = breast_cancer.data.features
y = breast_cancer.data.targets

# metadata
print(breast_cancer.metadata)

# variable information
print(breast_cancer.variables)

# Import required libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans, AgglomerativeClustering
from sklearn.metrics import silhouette_score

from scipy.cluster.hierarchy import dendrogram, linkage

data = load_breast_cancer()
df = pd.DataFrame(data.data, columns=data.feature_names)

print("First five rows of dataset:")
print(df.head())

scaler = StandardScaler()
X_scaled = scaler.fit_transform(df)

"""Applying k means clustering"""

kmeans = KMeans(n_clusters=2, random_state=42)  #malignant or benign
kmeans_labels = kmeans.fit_predict(X_scaled)

df['KMeans_Cluster'] = kmeans_labels

kmeans_silhouette = silhouette_score(X_scaled, kmeans_labels)
print("\nK-Means Silhouette Score:", kmeans_silhouette)

"""Heirarchichal Clusternign"""

hierarchical = AgglomerativeClustering(n_clusters=2)
hierarchical_labels = hierarchical.fit_predict(X_scaled)

df['Hierarchical_Cluster'] = hierarchical_labels

hierarchical_silhouette = silhouette_score(X_scaled, hierarchical_labels)
print("Hierarchical Clustering Silhouette Score:", hierarchical_silhouette)

#dendogram drawing
plt.figure(figsize=(10,5))
linked = linkage(X_scaled, method='ward')
dendrogram(linked)
plt.title("Hierarchical Clustering Dendrogram")
plt.xlabel("Samples")
plt.ylabel("Distance")
plt.show()

"""2D"""

plt.figure(figsize=(12,5))

# KMeans Plot
plt.subplot(1,2,1)
plt.scatter(X_scaled[:,0], X_scaled[:,1], c=kmeans_labels, cmap='viridis')
plt.title("K-Means Clustering")
plt.xlabel("Feature 1")
plt.ylabel("Feature 2")

plt.subplot(1,2,2)
plt.scatter(X_scaled[:,0], X_scaled[:,1], c=hierarchical_labels, cmap='rainbow')
plt.title("Hierarchical Clustering")
plt.xlabel("Feature 1")
plt.ylabel("Feature 2")

plt.show()

df1 = pd.read_csv("Iris.csv")

df1 = df1.drop("Id", axis =1)

df.head()

scaler = StandardScaler()

X_scaled = scaler.fit_transform(df1[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']])

kmeans_iris = KMeans(n_clusters=3, random_state=42) # Iris has 3 species
kmeans_labels_iris = kmeans_iris.fit_predict(X_scaled)

df1['KMeans_Cluster'] = kmeans_labels_iris
# Evaluate K-Means
kmeans_silhouette_iris = silhouette_score(X_scaled, kmeans_labels_iris)
print("K-Means Silhouette Score for Iris:", kmeans_silhouette_iris)

# Hierarchical Clustering
hierarchical_iris = AgglomerativeClustering(n_clusters=3)
hierarchical_labels_iris = hierarchical_iris.fit_predict(X_scaled)

df1['Hierarchical_Cluster'] = hierarchical_labels_iris

# Evaluate Hierarchical clustering
hierarchical_silhouette_iris = silhouette_score(X_scaled, hierarchical_labels_iris)
print("Hierarchical Clustering Silhouette Score for Iris:", hierarchical_silhouette_iris)

# Dendrogram for Hierarchical Clustering
plt.figure(figsize=(10,5))
linked = linkage(X_scaled, method='ward')
dendrogram(linked)
plt.title("Hierarchical Clustering Dendrogram")
plt.xlabel("Samples")
plt.ylabel("Distance")
plt.show()

# Visualization of Clusters
plt.figure(figsize=(12,5))
# KMeans Plot
plt.subplot(1,2,1)
plt.scatter(X_scaled[:,0],
X_scaled[:,1],
c=kmeans_labels_iris, cmap='viridis')
plt.title("K-Means Clustering (Iris Dataset)")
plt.xlabel("Feature 1")
plt.ylabel("Feature 2")
# Hierarchical Plot
plt.subplot(1,2,2)
plt.scatter(X_scaled[:,0],
X_scaled[:,1],
c=hierarchical_labels_iris, cmap='rainbow')
plt.title("Hierarchical Clustering (Iris Dataset)")
plt.xlabel("Feature 1")
plt.ylabel("Feature 2")
plt.show()

